export class Camera {
 zoomOverride?: (delta:number)=>boolean;
 minRadius=3.2;maxRadius=180;
 az=.45;el=.16;logR=Math.log(38);target=[.45,.16,Math.log(38)];pan=[0,0];targetPan=[0,0];drag=false;private pointers=new Map<number,number[]>();private clean:()=>void;
 constructor(public canvas:HTMLCanvasElement){let last=[0,0],pinch=0;const down=(e:PointerEvent)=>{canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);last=[e.clientX,e.clientY];this.drag=true;};const move=(e:PointerEvent)=>{if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(this.pointers.size===2){const p=[...this.pointers.values()],d=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);if(pinch)this.target[2]+=Math.log(pinch/d);pinch=d;}else{const dx=e.clientX-last[0],dy=e.clientY-last[1];if(e.shiftKey||e.buttons===2){this.targetPan[0]-=dx*.001;this.targetPan[1]+=dy*.001;}else{const sensitivity=.003*Math.min(1,Math.exp(this.logR)/12);this.target[0]-=dx*sensitivity;this.target[1]+=dy*sensitivity;}}last=[e.clientX,e.clientY];this.clamp();};const up=(e:PointerEvent)=>{this.pointers.delete(e.pointerId);this.drag=this.pointers.size>0;pinch=0;};const wheel=(e:WheelEvent)=>{e.preventDefault();if(this.zoomOverride?.(e.deltaY))return;this.target[2]+=Math.max(-.3,Math.min(.3,e.deltaY*.001));this.clamp();};const context=(e:Event)=>e.preventDefault();canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('contextmenu',context);this.clean=()=>{canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);canvas.removeEventListener('wheel',wheel);canvas.removeEventListener('contextmenu',context);};}
 clamp(){this.target[1]=Math.max(-1.55,Math.min(1.55,this.target[1]));this.target[2]=Math.max(Math.log(this.minRadius),Math.min(Math.log(this.maxRadius),this.target[2]));this.targetPan=this.targetPan.map(x=>Math.max(-1.2,Math.min(1.2,x)));}
 preset(p:number[]){this.target=[p[0]+Math.round((this.az-p[0])/(2*Math.PI))*2*Math.PI,p[1],Math.log(p[2])];this.targetPan=[p[3]||0,p[4]||0];}
 update(dt:number,orbit:boolean){if(orbit&&!this.drag)this.target[0]+=dt*.025;const k=1-Math.exp(-dt*5);this.az+=(this.target[0]-this.az)*k;this.el+=(this.target[1]-this.el)*k;this.logR+=(this.target[2]-this.logR)*k;this.pan=this.pan.map((x,i)=>x+(this.targetPan[i]-x)*k);}
 get position(){const r=Math.exp(this.logR);return [r*Math.cos(this.el)*Math.sin(this.az),r*Math.sin(this.el),r*Math.cos(this.el)*Math.cos(this.az)];}
 destroy(){this.clean();}
}
