import {Settings} from './state';
import {vertex} from './shaders';
import {fieldGeometry,FieldLine,magneticWorld,neutronPhysics} from './neutron';
import {fieldVertex,fieldFragment,neutronFragment} from './neutron-shader';
export type NeutronFrame={eye:number[];pan:number[];time:number;phase:number;flare:number;flareAge:number;settings:Settings;fade:number};
/** Dedicated GPU pass: ray-evaluated crust and beams, then antialiased 3D field ribbons. */
export class NeutronRenderer{
 private surface:WebGLProgram;private fields:WebGLProgram;private quad:WebGLVertexArrayObject;private ribbons:WebGLVertexArrayObject;private buffer:WebGLBuffer;private quadBuffer:WebGLBuffer;private count=0;private uniforms=new Map<string,WebGLUniformLocation|null>();
 constructor(private gl:WebGL2RenderingContext){
  const program=(v:string,f:string)=>{const p=gl.createProgram()!;for(const [type,source]of [[gl.VERTEX_SHADER,v],[gl.FRAGMENT_SHADER,f]] as [number,string][]){const s=gl.createShader(type)!;gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||'Neutron shader failed');gl.attachShader(p,s);gl.deleteShader(s);}gl.bindAttribLocation(p,0,'position');gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'Neutron link failed');return p;};
  this.surface=program(vertex,neutronFragment);this.fields=program(fieldVertex,fieldFragment);
  this.quad=gl.createVertexArray()!;gl.bindVertexArray(this.quad);this.quadBuffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,this.quadBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);
  this.ribbons=gl.createVertexArray()!;gl.bindVertexArray(this.ribbons);this.buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);for(let i=0;i<3;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,i===2?4:3,gl.FLOAT,false,40,i*12);}gl.bindVertexArray(null);
 }
 private geometryKey='';
 private rebuild(s:Settings){const physics=neutronPhysics(s),twist=s.object==='magnetar'?s.magneticTwist:0,key=[s.object,twist,s.period,s.nsRadius].join(':');if(this.geometryKey===key)return;this.geometryKey=key;const vertices:number[]=[];for(const line of fieldGeometry(twist,s.object,physics.lightCylinder/physics.R)){const n=line.points.length;for(let i=0;i<n-1;i++)for(const [index,side] of [[i,-1],[i+1,-1],[i,1],[i,1],[i+1,-1],[i+1,1]]){const p=line.points[index],a=line.points[Math.max(0,index-1)],b=line.points[Math.min(n-1,index+1)];vertices.push(...p,...b.map((x,j)=>x-a[j]),side,index/(n-1),line.id,line.shell);}}this.count=vertices.length/10;this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.buffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array(vertices),this.gl.STATIC_DRAW);}
 render(frame:NeutronFrame,w:number,h:number){const g=this.gl,s=frame.settings;this.rebuild(s);g.disable(g.DEPTH_TEST);g.disable(g.BLEND);
  for(const [p,key]of [[this.surface,'s'],[this.fields,'f']] as const){g.useProgram(p);const loc=(n:string)=>{const k=key+n;if(!this.uniforms.has(k))this.uniforms.set(k,g.getUniformLocation(p,n));return this.uniforms.get(k)!;};g.uniform3fv(loc('eye'),frame.eye);g.uniform2fv(loc('pan'),frame.pan);g.uniform2f(loc('resolution'),w,h);
   const values={time:frame.time,phase:frame.phase,magneticTwist:s.magneticTwist,flare:frame.flare,flareAge:frame.flareAge,fade:frame.fade,fov:s.fov,tilt:s.tilt,roll:s.roll,obliquity:s.obliquity,fieldLog:s.fieldLog,nsCompactness:neutronPhysics(s).compactness,beamAngle:s.beamAngle,flowRate:s.flowRate,fieldIntensity:s.fieldIntensity,exposure:s.exposure,stars:s.stars,lineWidth:(s.object==='magnetar'?4.8:3.8)*Math.max(.75,w/(g.canvas as HTMLCanvasElement).clientWidth)};
   for(const [k,v]of Object.entries(values))g.uniform1f(loc(k),v);for(const [k,v]of Object.entries({magnetar:s.object==='magnetar',beams:s.beams,fieldLines:s.fieldLines,flowParticles:s.flowParticles}))g.uniform1i(loc(k),+v);
   if(key==='s'){g.bindVertexArray(this.quad);g.drawArrays(g.TRIANGLES,0,3);}else if(s.fieldLines){g.enable(g.BLEND);g.blendFunc(g.ONE,g.ONE);g.bindVertexArray(this.ribbons);g.drawArrays(g.TRIANGLES,0,this.count);g.disable(g.BLEND);}
  }g.bindVertexArray(null);
 }
 destroy(){const g=this.gl;g.deleteProgram(this.surface);g.deleteProgram(this.fields);g.deleteBuffer(this.buffer);g.deleteBuffer(this.quadBuffer);g.deleteVertexArray(this.quad);g.deleteVertexArray(this.ribbons);}
}
/** Responsive compatibility view: same dipole geometry, projected/occluded in 3D.
 * Surface and beam appearance are simplified; this is explicitly identified in diagnostics. */
export class NeutronCanvas{
 private lines:FieldLine[]=[];private geometryKey='';private surface:HTMLCanvasElement;private surfaceTime=-1;private surfaceKey='';private stars=Array.from({length:370},(_,i)=>{const h=(x:number)=>{const v=Math.sin(x*127.1)*43758.5453;return v-Math.floor(v);};const y=h(i+13)*2-1,a=h(i+27)*Math.PI*2;return [Math.sqrt(1-y*y)*Math.cos(a),y,Math.sqrt(1-y*y)*Math.sin(a),h(i+87)];});
 constructor(){this.surface=document.createElement('canvas');this.surface.width=this.surface.height=240;}
 render(ctx:CanvasRenderingContext2D,f:NeutronFrame,w:number,h:number){const s=f.settings,mag=s.object==='magnetar',twist=mag?s.magneticTwist:0;const physics=neutronPhysics(s),geometryKey=[s.object,twist,s.period,s.nsRadius].join(':');if(geometryKey!==this.geometryKey){this.geometryKey=geometryKey;this.lines=fieldGeometry(twist,s.object,physics.lightCylinder/physics.R);}const eye=f.eye,r=Math.hypot(...eye),forward=eye.map(x=>-x/r),rl=Math.hypot(forward[0],forward[2]),right=[-forward[2]/rl,0,forward[0]/rl],up=[right[1]*forward[2]-right[2]*forward[1],right[2]*forward[0]-right[0]*forward[2],right[0]*forward[1]-right[1]*forward[0]],dot=(a:number[],b:number[])=>a.reduce((v,x,i)=>v+x*b[i],0),scale=h/(2*Math.tan(s.fov*Math.PI/360));
 const project=(p:number[])=>{const v=p.map((x,i)=>x-eye[i]),z=dot(v,forward);return z>.08?[w/2+scale*dot(v,right)/z-f.pan[0]*h/2,h/2-scale*dot(v,up)/z+f.pan[1]*h/2,z]:null;};
 const world=(p:number[])=>magneticWorld(p,f.phase,s.obliquity,s.tilt,s.roll);
 const occluded=(p:number[])=>{const v=p.map((x,i)=>x-eye[i]),d=Math.hypot(...v),b=dot(eye,v)/d,disc=b*b-r*r+1;return disc>0&&-b-Math.sqrt(disc)<d-.02;};
 ctx.globalCompositeOperation='source-over';ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);ctx.globalAlpha=f.fade;
 for(const star of this.stars){const p=project(star.slice(0,3).map(x=>x*200));if(p&&p[2]>0){ctx.fillStyle=`rgba(196,204,216,${(.15+star[3]*.6)*s.stars})`;ctx.fillRect(p[0],p[1],star[3]>.98?1.3:.7,star[3]>.98?1.3:.7);}}
 const center=project([0,0,0])!;const radius=scale/Math.sqrt(r*r-1),rgb=mag?'255,154,65':'91,164,255';
 // Render both magnetic-axis beams as perspective-projected nested emissivity cones.
 ctx.globalCompositeOperation='lighter';if(s.beams)for(const sign of [-1,1]){for(let layer=6;layer>=0;layer--){ctx.beginPath();let started=false;for(let j=0;j<=60;j++){const z=1+j*.38,p=world([0,z*sign,0]),xy=project(p);if(!xy||occluded(p)){started=false;continue;}if(!started)ctx.moveTo(xy[0],xy[1]);else ctx.lineTo(xy[0],xy[1]);started=true;}ctx.lineWidth=(1+layer*layer*.65)*(s.beamAngle/9)*Math.min(2.2,28/r);ctx.strokeStyle=`rgba(${layer<2?'204,228,255':rgb},${(mag?.025:.12)*(1+f.flare)*s.exposure})`;ctx.stroke();}}
 const halo=ctx.createRadialGradient(center[0],center[1],radius*.93,center[0],center[1],radius*1.9);halo.addColorStop(0,`rgba(${rgb},.6)`);halo.addColorStop(.1,`rgba(${rgb},.1)`);halo.addColorStop(1,`rgba(${rgb},0)`);ctx.fillStyle=halo;ctx.fillRect(center[0]-radius*2,center[1]-radius*2,radius*4,radius*4);
 ctx.globalCompositeOperation='source-over';
 const surfaceKey=[mag,s.nsMass,s.nsRadius,s.obliquity,s.tilt,s.roll,s.exposure,...eye.map(x=>x.toFixed(2))].join(':');if(f.time-this.surfaceTime>.08||surfaceKey!==this.surfaceKey||f.time<this.surfaceTime){this.surfaceTime=f.time;this.surfaceKey=surfaceKey;const size=240,redshiftFactor=1.9*((1-physics.compactness)/(1-physics.compactness/r))**2,c=this.surface.getContext('2d')!,img=c.createImageData(size,size),axis=world([0,1,0]);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const nx=(x+.5)/size*2-1,ny=1-(y+.5)/size*2,q=nx*nx+ny*ny;if(q>1)continue;const nz=Math.sqrt(1-q),n=right.map((a,i)=>a*nx+up[i]*ny-forward[i]*nz),u=dot(n,axis),grain=.5+.5*Math.sin(n[0]*122+Math.sin(n[1]*69)*2)*Math.sin(n[2]*137+f.phase),vein=Math.pow(1-Math.abs(Math.sin(n[0]*29+Math.sin(n[1]*17)*2+n[2]*33)),10),hot=Math.pow(Math.abs(u),32),shade=(.28+.27*grain+.11*vein)*(.35+.65*nz)+hot*.7+f.flare*.18;const colors=mag?[1,.75,.47]:[.58,.76,1];for(let k=0;k<3;k++)img.data[(y*size+x)*4+k]=255*Math.sqrt(1-Math.exp(-shade*colors[k]*s.exposure*redshiftFactor));img.data[(y*size+x)*4+3]=255;}c.putImageData(img,0,0);}
 ctx.drawImage(this.surface,center[0]-radius,center[1]-radius,radius*2,radius*2);
 ctx.globalCompositeOperation='lighter';if(s.fieldLines)for(const line of this.lines){const projected=line.points.map(p=>{const wp=world(p);return occluded(wp)?null:project(wp);});ctx.beginPath();let started=false;for(const p of projected){if(!p){started=false;continue;}if(!started)ctx.moveTo(p[0],p[1]);else ctx.lineTo(p[0],p[1]);started=true;}const intensity=(mag?1:line.shell<0?1.45:.28)*s.fieldIntensity*(.7+(s.fieldLog-11)*.1)*s.exposure*(1+f.flare);for(const [width,alpha]of [[4,.035],[1.1,.35],[.45,.48]]){ctx.lineWidth=width;ctx.strokeStyle=`rgba(${rgb},${Math.min(1,alpha*intensity)})`;ctx.stroke();}
  if(s.flowParticles){const head=((f.time*s.flowRate*.32-line.id*.137)%1+1)%1;for(let packet=0;packet<3;packet++){const at=(head+packet/3)%1;ctx.beginPath();let begun=false;for(let k=0;k<9;k++){const index=Math.floor((at-k*.005)*112),p=index>=0?projected[index]:null;if(!p){begun=false;continue;}if(!begun)ctx.moveTo(p[0],p[1]);else ctx.lineTo(p[0],p[1]);begun=true;}ctx.lineWidth=1.45;ctx.strokeStyle=`rgba(${mag?'255,235,178':'197,229,255'},${Math.min(1,.85*intensity)})`;ctx.stroke();}}
 }
 if(mag&&f.flare>0){const rr=radius*(1+f.flareAge*5.5);ctx.beginPath();ctx.ellipse(center[0],center[1],rr,rr,0,0,Math.PI*2);ctx.lineWidth=3;ctx.strokeStyle=`rgba(255,189,103,${f.flare*.45})`;ctx.stroke();}
 ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;
 }
}
