export type CelestialObject = "black-hole" | "white-hole" | "star" | "wormhole" | "magnetar" | "pulsar";
export type Settings={object:CelestialObject;nsMass:number;nsRadius:number;period:number;fieldLog:number;obliquity:number;magneticTwist:number;fieldLines:boolean;flowParticles:boolean;beams:boolean;beamAngle:number;fieldIntensity:number;flowRate:number;rotationPlayback:number;tilt:number;roll:number;wormFold:boolean;wormCinematic:boolean;wormPosition:number;wormTravel:boolean;wormDirection:number;wormLookBack:boolean;wormStructure:boolean;throatKm:number;travelSpeed:number;colorContrast:boolean;jets:boolean;jetPower:number;jetSpeed:number;starMass:number;activity:number;rotation:number;limb:number;corona:number;granulation:number;whiteEmission:boolean;volume:number;source:number;outflow:number;outflowSpeed:number;spin:number;mass:number;intensity:number;turbulence:number;speed:number;exposure:number;bloom:number;stars:number;fov:number;renderScale:number;targetFps:number;lensing:boolean;doppler:boolean;redshift:boolean;disk:boolean;paths:boolean;enhanced:boolean;temperature:boolean;autoOrbit:boolean;quality:string;mode:string};
export const defaults:Settings={object:"black-hole",nsMass:1.4,nsRadius:12,period:5.2,fieldLog:14.8,obliquity:28,magneticTwist:.8,fieldLines:true,flowParticles:true,beams:true,beamAngle:7,fieldIntensity:1.4,flowRate:1,rotationPlayback:1,tilt:0,roll:0,wormFold:false,wormCinematic:true,wormPosition:12,wormTravel:false,wormDirection:-1,wormLookBack:false,wormStructure:false,throatKm:1000000,travelSpeed:.65,colorContrast:false,jets:false,jetPower:1,jetSpeed:.8,starMass:1,activity:.4,rotation:1,limb:.6,corona:.4,granulation:1,whiteEmission:false,volume:.55,source:1,outflow:.8,outflowSpeed:.5,spin:.6,mass:100000000,intensity:1.35,turbulence:.7,speed:1,exposure:1.15,bloom:.16,stars:1,fov:44,renderScale:1,targetFps:60,lensing:true,doppler:true,redshift:true,disk:true,paths:false,enhanced:false,temperature:false,autoOrbit:false,quality:'AUTO',mode:'PHYSICAL'};
export const presets:Record<string,number[]>={'Distant observer':[.45,.23,55],'Polar':[.45,1.48,48],'Equatorial':[.45,.035,30],'Photon region':[.45,.22,8],'Cinematic':[.45,.16,38],'Disk-side passage':[.6,.07,9,-.85,.04],'Extreme lensing':[.45,-.08,5]};
export function isco(a:number){const z1=1+Math.cbrt(1-a*a)*(Math.cbrt(1+a)+Math.cbrt(1-a)),z2=Math.sqrt(3*a*a+z1*z1);return (3+z2-Math.sqrt((3-z1)*(3+z1+2*z2)))/2;}

export const objectCatalog = {"magnetar":{id:"MG—05",name:"Magnetar",designation:"ULTRA-STRONG MAGNETIC FIELD",description:"Twisted near-zone magnetosphere"},"pulsar":{id:"PS—06",name:"Pulsar",designation:"ROTATING NEUTRON STAR",description:"Oblique magnetic lighthouse"},"wormhole":{id:"ER—04",name:"Ellis wormhole",designation:"TWO ASYMPTOTIC REGIONS",description:"Hypothetical · traversable geometry"},"star":{id:"ST—03",name:"Main-sequence star",designation:"STELLAR PHOTOSPHERE",description:"Empirical dwarf sequence"},"black-hole":{id:"BH—01",name:"Black hole",designation:"SCHWARZSCHILD OPTICS",description:"Spin-dependent accretion disk"},"white-hole":{id:"WH—02",name:"White hole",designation:"TIME-REVERSED BRANCH",description:"Hypothetical · prescribed emission"}} as const;

export function factorySettings(object:CelestialObject):Settings{return {...defaults,object,whiteEmission:object==="white-hole",source:object==="white-hole"?1.35:1,outflow:object==="white-hole"?1.2:.8,paths:false,...(object==="magnetar"?{tilt:16,roll:-18,exposure:1.3,fieldIntensity:1.8,beams:false,beamAngle:5,mode:"OBSERVATIONAL"}:object==="pulsar"?{period:.089,fieldLog:12.5,obliquity:58,magneticTwist:0,rotationPlayback:.018,beamAngle:6,tilt:10,roll:22,exposure:1.2,mode:"OBSERVATIONAL"}:{})};}
