'use client';
import {Settings} from '@/lib/observatory/state';
import {neutronPhysics,observerPulse} from '@/lib/observatory/neutron';
import {scientific} from '@/lib/observatory/formulas';
import {MathFormula} from './formula-panel';
export const neutronEquations=[
 ['Dipole field',String.raw`B_r=B_{\rm p}\left(\frac{R}{r}\right)^3\cos\theta,\quad B_\theta=\frac{B_{\rm p}}{2}\left(\frac{R}{r}\right)^3\sin\theta`,'Near-zone vacuum dipole. Twisted lines are an illustrative deformation, not a force-free magnetosphere solution.'],
 ['Closed field lines',String.raw`r=L\sin^2\theta`,'Integrated dipole geometry. L is each line’s equatorial crossing radius; moving packets trace the lines, not motion of magnetic field itself.'],
 ['Rotation frequency',String.raw`\nu=\frac{1}{P},\qquad\Omega=\frac{2\pi}{P}`,'Physical period is kept separate from the slowed display clock.'],
 ['Light cylinder',String.raw`R_{\rm LC}=\frac{c}{\Omega}=\frac{cP}{2\pi}`,'The radius at which rigid corotation would reach c. The displayed field is restricted to the inner magnetosphere; an outer wind is not simulated.'],
 ['Surface gravitational redshift',String.raw`g=\sqrt{\frac{1-r_s/R}{1-r_s/r_o}},\quad I_{\rm bol,o}=g^4I_{\rm bol,e}`,'Static spherical transfer to observer radius r_o. The reported surface z is relative to infinity. No surface light bending, atmosphere spectrum or full pulse-profile transfer.'],
 ['Magnetic energy density',String.raw`u_B=\frac{B^2}{2\mu_0}`,'SI calculation after converting gauss to tesla. Surface polar value; not the total stored magnetic energy.'],
 ['Mean density',String.raw`\bar\rho=\frac{3M}{4\pi R^3}`,'Mass and radius are illustrative neutron-star parameters, not an equation-of-state inference.']
] as const;
export function NeutronFormulas({settings:s,onClose}:{settings:Settings;onClose:()=>void}){const p=neutronPhysics(s),outputs=[`${scientific(p.B)} G at the pole`, 'Displayed shells: 2.05–8.8 R',`${p.frequency.toFixed(3)} Hz`,`${scientific(p.lightCylinder/1000)} km`,`z∞ = ${p.redshift.toFixed(3)}`,`${scientific((p.B*1e-4)**2/(2*4*Math.PI*1e-7))} J m⁻³`,`${scientific(p.density)} kg m⁻³`];return <aside className="formula-panel neutron-formulas"><div className="formula-heading"><div><span className="eyebrow">NEUTRON-STAR PHYSICS</span><h2>{s.object==='magnetar'?'Magnetic dominion':'The cosmic lighthouse'}</h2></div><button onClick={onClose} aria-label="Close formulas">×</button></div><div className="formula-inputs">{s.nsMass.toFixed(2)} M☉ · {s.nsRadius.toFixed(1)} km · {s.period} s</div><div className="formula-scroll">{neutronEquations.map(([name,tex,note],i)=><section className="formula-row" key={name}><h3>{name}</h3><MathFormula tex={tex}/><output>{outputs[i]}</output><p>{note}</p></section>)}</div><a href="/physics.html#neutron" target="_blank" rel="noreferrer">Sources & model limitations</a></aside>;}
export function NeutronReadout({settings:s,phase,pulse,eye,distance,height,onChange,onFlare}:{settings:Settings;phase:number;pulse:number;eye:number[];distance:number;height:number;onChange:<K extends keyof Settings>(k:K,v:Settings[K])=>void;onFlare:()=>void}){const mag=s.object==='magnetar',p=neutronPhysics(s),curve=Array.from({length:160},(_,i)=>{const y=observerPulse(eye,s,phase-(159-i)/159*Math.PI*4);return `${i*240/159},${42-y*36}`;}).join(' '),scale=height/(2*Math.tan(s.fov*Math.PI/360)*distance)*(10/s.nsRadius);return <>
 <div className="neutron-note">{mag?'MAGNETIC DOMINION':'THE COSMIC LIGHTHOUSE'}<span>Field & radiation visualization · enhanced visibility</span></div>
 <div className="neutron-console"><div className="neutron-console-top"><span>{mag?'INNER MAGNETOSPHERE':'OBSERVER SIGNAL'}</span><strong>{mag?`${scientific(p.B)} G`:`${(pulse*100).toFixed(0)}%`}</strong></div>{!mag&&<svg viewBox="0 0 240 48" role="img" aria-label="Modeled observer pulse over two rotations"><path d="M0 42H240" stroke="#ffffff20" fill="none"/><polyline points={curve} stroke="#c6dfec" strokeWidth="1.2" fill="none"/></svg>}<div className="neutron-actions"><button aria-pressed={s.fieldLines} onClick={()=>onChange('fieldLines',!s.fieldLines)}>FIELD {s.fieldLines?'ON':'OFF'}</button><button aria-pressed={s.flowParticles} onClick={()=>onChange('flowParticles',!s.flowParticles)}>FLOW {s.flowParticles?'ON':'OFF'}</button>{mag?<button onClick={onFlare}>TRIGGER FLARE</button>:<button aria-pressed={s.beams} onClick={()=>onChange('beams',!s.beams)}>BEAMS {s.beams?'ON':'OFF'}</button>}</div><p>{mag?'Twisted current bundles · illustrative flare dynamics':`${p.frequency.toFixed(2)} Hz physical · ${(s.rotationPlayback*s.speed).toFixed(3)}× playback`}</p></div>
 <div className="neutron-scale"><span style={{width:Math.max(2,scale)}}/><strong>10 km</strong><small>AT STELLAR CENTER DISTANCE</small></div>
 </>;}
