'use client';
import {Settings} from '@/lib/observatory/state';
import {Slider} from '@/components/ui/slider';
export function WormholeControls({settings,l,travel,change}:{settings:Settings;l:number;travel:boolean;change:<K extends keyof Settings>(k:K,v:Settings[K])=>void}){
 const view=settings.wormFold?'fold':settings.wormStructure?'structure':'optical';
 const choose=(v:string)=>{change('wormFold',v==='fold');change('wormStructure',v==='structure');};
 return <div className="worm-controls"><div className="worm-heading"><span className="eyebrow">ELLIS PASSAGE</span><span>{l>.05?'REGION A':l<-.05?'REGION B':'THROAT'} · ℓ/a = {l.toFixed(2)}</span></div><div className="worm-view-tabs">{[['optical','Optical'],['structure','Structure'],['fold','Folded space']].map(([v,label])=><button key={v} aria-pressed={view===v} onClick={()=>choose(v)}>{label}</button>)}</div><div className="journey-track"><span>A</span><Slider aria-label="Wormhole proper distance" min={-12} max={12} step={.05} value={[-l]} onValueChange={v=>{change('wormTravel',false);change('wormPosition',-v[0]);}}/><span>B</span></div><div className="worm-buttons"><button onClick={()=>{if(!travel){change('wormPosition',l);if(Math.abs(l)>11.9)change('wormDirection',l>0?-1:1);}change('wormTravel',!travel);}}>{travel?'Pause passage':Math.abs(l)>11.9?(l>0?'Traverse to B':'Return to A'):'Continue passage'}</button><button aria-pressed={settings.wormLookBack} onClick={()=>change('wormLookBack',!settings.wormLookBack)}>{settings.wormLookBack?'Look forward':'Look behind'}</button><button aria-pressed={settings.paths} onClick={()=>change('paths',!settings.paths)}>Photon paths {settings.paths?'ON':'OFF'}</button></div><label className="worm-cinema"><input type="checkbox" checked={settings.wormCinematic} onChange={e=>change('wormCinematic',e.target.checked)}/> Cinematic passage · ease through throat</label><p>{view==='fold'?'Folded-sheet analogy · long exterior route versus throat shortcut':view==='structure'?'Isometric equatorial embedding · not physical tunnel walls':'Hypothetical spacetime · continuously integrated null geodesics'}<br/>Exotic stress-energy required · illustrative camera speed</p></div>
}
export function StellarScale({distance,fov,height}:{distance:number;fov:number;height:number}){const kmPerPx=2*distance*Math.tan(fov*Math.PI/360)*695700/Math.max(1,height),raw=kmPerPx*110,power=10**Math.floor(Math.log10(raw)),nice=[5,2,1].find(x=>x*power<=raw)??1,km=nice*power;return <div className="stellar-scale"><span style={{width:km/kmPerPx}}/><strong>{km.toLocaleString(undefined,{maximumFractionDigits:0})} km</strong><small>AT CENTER PLANE</small></div>}
