import fs from 'node:fs';import ts from 'typescript';import assert from 'node:assert/strict';
const code=ts.transpileModule(fs.readFileSync('lib/observatory/quality.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const {AdaptiveResolution,renderDimensions,GpuTimer}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
assert.equal(renderDimensions(1366,1024,2,1).w,2732);assert.equal(renderDimensions(1366,1024,2,1.25,16000000).w,3415);
for(const dpr of [1,2,3,4])for(const [w,h]of [[1366,1024],[3840,2160],[430,932]]){const r=renderDimensions(w,h,dpr,1.25,16000000,4096);assert(r.w<=4096&&r.h<=4096);assert(r.w*r.h<=16000000);assert(Math.abs(r.w/r.h-w/h)<.01);}
const q=new AdaptiveResolution();q.select('BH',0);for(let t=0;t<12000;t+=100)q.sample(45,t,60,.3,true);assert(q.factor<.7&&q.factor>=.3);const slow=q.factor;q.select('star',12000);assert.equal(q.factor,1);q.select('BH',14000);assert.equal(q.factor,slow);for(let t=15000;t<150000;t+=100)q.sample(4,t,60,.3,true);assert.equal(q.factor,1);q.reset(150000);assert.equal(q.factor,1);
const hidden=new AdaptiveResolution();hidden.select('BH',0);for(let t=3000;t<30000;t+=100)hidden.sample(5000,t,60,.3,false);assert.equal(hidden.factor,1);
let available=false,disjoint=false,deleted=0;const gl={getExtension:()=>({TIME_ELAPSED_EXT:1,GPU_DISJOINT_EXT:2}),createQuery:()=>({}),beginQuery(){},endQuery(){},getParameter:()=>disjoint,getQueryParameter:(q,k)=>k===3?available:12000000,QUERY_RESULT_AVAILABLE:3,QUERY_RESULT:4,deleteQuery(){deleted++}};const timer=new GpuTimer(gl);timer.begin();timer.end();assert.equal(timer.poll(),null);available=true;assert.equal(timer.poll(),12);assert.equal(deleted,1);for(let i=0;i<4;i++){timer.begin();timer.end();}disjoint=true;assert.equal(timer.poll(),null);assert.equal(timer.ms,0);
console.log('PASS: native/high-DPI and ULTRA dimensions, pixel/hardware budgets, aspect ratio, load reduction, recovery, scene isolation, long-gap rejection and asynchronous/disjoint GPU queries');
