import fs from 'node:fs';import assert from 'node:assert/strict';import ts from 'typescript';import katex from 'katex';
const tmp='/workspace/scratch/181e94992846/neutron-qa';fs.mkdirSync(tmp,{recursive:true});
for(const name of ['state','orientation','neutron','shaders','neutron-shader']){const source=fs.readFileSync(`lib/observatory/${name}.ts`,'utf8').replace(/from '\.\/(.*?)'/g,"from './$1.mjs'");fs.writeFileSync(`${tmp}/${name}.mjs`,ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText);}
const {factorySettings}=await import(`${tmp}/state.mjs`),n=await import(`${tmp}/neutron.mjs`),sh=await import(`${tmp}/neutron-shader.mjs`),{vertex}=await import(`${tmp}/shaders.mjs`);
for(const object of ['magnetar','pulsar']){const s=factorySettings(object);assert.equal(s.object,object);const p=n.neutronPhysics(s);assert(p.compactness>0&&p.compactness<1);assert(p.lightCylinder/p.R>8.8);assert(p.redshift>.2&&p.redshift<.4);assert(Math.abs(p.bolometricIntensityFactor-(1-p.compactness)**2)<1e-12);assert(s.beams===(object==='pulsar'));assert(s.fieldLines&&s.flowParticles);}
for(const nsMass of [1.1,2.2])for(const nsRadius of [10,14])for(const period of [.02,12]){const p=n.neutronPhysics({nsMass,nsRadius,period,fieldLog:15.5});assert(p.compactness<.67);assert(p.lightCylinder/p.R>8.8);}
for(const twist of [0,.8,1.8])for(const line of n.fieldGeometry(twist)){assert(line.points.every(p=>p.every(Number.isFinite)));assert(Math.abs(Math.hypot(...line.points[0])-1.015)<1e-8);assert(Math.abs(Math.hypot(...line.points.at(-1))-1.015)<1e-8);if(twist===0){const L=Math.hypot(...line.points[56]);for(const p of line.points){const r=Math.hypot(...p);assert(Math.abs(r-L*(1-(p[1]/r)**2))<1e-10);}}}
const s=factorySettings('pulsar'),axis=n.magneticWorld([0,1,0],.3,s.obliquity,s.tilt,s.roll);assert(Math.abs(Math.hypot(...axis)-1)<1e-12);assert(n.observerPulse(axis,s,.3)>.999);assert(n.observerPulse(axis,{...s,beams:false},.3)===0);assert(n.observerPulse(axis,s,.3+Math.PI)<.01);
let count=0;for(const file of ['components/neutron-instruments.tsx','components/formula-panel.tsx','components/wormhole-formulas.tsx'])for(const m of fs.readFileSync(file,'utf8').matchAll(/String\.raw`([^`]*)`/g)){katex.renderToString(m[1],{throwOnError:true,strict:'error'});count++;}
function mesh(twist,kind){const out=[];for(const line of n.fieldGeometry(twist,kind,n.neutronPhysics(factorySettings(kind)).lightCylinder/n.neutronPhysics(factorySettings(kind)).R)){const N=line.points.length;for(let i=0;i<N-1;i++)for(const [k,side]of [[i,-1],[i+1,-1],[i,1],[i,1],[i+1,-1],[i+1,1]]){const a=line.points[Math.max(0,k-1)],b=line.points[Math.min(N-1,k+1)];out.push(...line.points[k],...b.map((v,j)=>v-a[j]),side,k/(N-1),line.id,line.shell);}}return out;}
fs.writeFileSync(`${tmp}/render.json`,JSON.stringify({vertex,...sh,magnetar:factorySettings('magnetar'),pulsar:factorySettings('pulsar')}));for(const kind of ['magnetar','pulsar'])fs.writeFileSync(`${tmp}/field-${kind}.bin`,Buffer.from(new Float32Array(mesh(kind==='magnetar'?.8:0,kind)).buffer));
console.log(`PASS: parameter limits, closed-field geometry, unit axes, observer-dependent pulses, per-object defaults and ${count} strict KaTeX formulas`);

for(const period of [.02,2]){const p=n.neutronPhysics({...factorySettings('pulsar'),period});const lines=n.fieldGeometry(0,'pulsar',p.lightCylinder/p.R);assert(lines.some(l=>l.shell<0));for(const l of lines.filter(l=>l.shell<0)){assert(Math.abs(Math.hypot(...l.points.at(-1))-23)<1e-8);assert(Math.hypot(...l.points.at(-1))<p.lightCylinder/p.R);}}
assert(n.fieldGeometry(.8).length>n.fieldGeometry(0,'pulsar').length);
